CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100),
    type VARCHAR(20) NOT NULL,
    price_precision INT DEFAULT 2,
    pip_size DOUBLE PRECISION DEFAULT 0.01
);

CREATE TABLE IF NOT EXISTS data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO data_sources (name, description)
VALUES ('default', 'Unspecified source')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS candles (
    id BIGSERIAL,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    timeframe VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION DEFAULT 0,
    PRIMARY KEY (instrument_id, timeframe, source_id, timestamp)
);

SELECT create_hypertable('candles', 'timestamp', if_not_exists => TRUE);

-- Idempotent migration for pre-source candles tables.
DO $migrate_candles$
DECLARE
    default_source_id BIGINT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'candles' AND column_name = 'source_id'
    ) THEN
        SELECT id INTO default_source_id FROM data_sources WHERE name = 'default';

        ALTER TABLE candles ADD COLUMN source_id BIGINT REFERENCES data_sources(id);
        UPDATE candles SET source_id = default_source_id WHERE source_id IS NULL;
        ALTER TABLE candles ALTER COLUMN source_id SET NOT NULL;

        ALTER TABLE candles DROP CONSTRAINT IF EXISTS candles_pkey;
        ALTER TABLE candles ADD PRIMARY KEY (instrument_id, timeframe, source_id, timestamp);

        -- Old index (without source_id) is now redundant with the new PK; drop it.
        DROP INDEX IF EXISTS idx_candles_lookup;
    END IF;
END
$migrate_candles$;

CREATE INDEX IF NOT EXISTS idx_candles_lookup ON candles(instrument_id, timeframe, source_id, timestamp);

CREATE TABLE IF NOT EXISTS data_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    timeframe VARCHAR(10) NOT NULL,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    row_count INT NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_data_imports_source ON data_imports(source_id, imported_at DESC);

CREATE TABLE IF NOT EXISTS backtest_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_symbol VARCHAR(20) NOT NULL,
    strategy_name VARCHAR(50) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    data_source VARCHAR(50) NOT NULL DEFAULT 'default',
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    initial_capital DOUBLE PRECISION NOT NULL,
    final_equity DOUBLE PRECISION NOT NULL,
    total_return_pct DOUBLE PRECISION,
    sharpe_ratio DOUBLE PRECISION,
    max_drawdown_pct DOUBLE PRECISION,
    total_trades INT,
    win_rate DOUBLE PRECISION,
    result_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE backtest_results ADD COLUMN IF NOT EXISTS data_source VARCHAR(50) NOT NULL DEFAULT 'default';
