const crypto = require('crypto');
const { pool } = require('./db');

const KNOWN_DOCS = new Set(['README', 'ARCHITECTURE']);

async function ensureSchema() {
  // Owned by the web layer, not the Java backtester. Idempotent.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS doc_revisions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      doc_name VARCHAR(50) NOT NULL,
      content TEXT NOT NULL,
      content_hash CHAR(64) NOT NULL,
      captured_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `);
  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS uq_doc_revisions_name_hash
      ON doc_revisions(doc_name, content_hash)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_doc_revisions_lookup
      ON doc_revisions(doc_name, captured_at DESC)
  `);
}

function hashContent(content) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

function assertKnownDoc(name) {
  if (!KNOWN_DOCS.has(name)) {
    const err = new Error(`unknown doc: ${name}`);
    err.status = 404;
    throw err;
  }
}

// Insert a new revision only if the latest one for this doc has a different
// content hash. Returns { id, captured_at, isNew }.
async function captureIfChanged(name, content) {
  assertKnownDoc(name);
  const hash = hashContent(content);

  const existing = await pool.query(
    `SELECT id, captured_at FROM doc_revisions
      WHERE doc_name = $1 AND content_hash = $2
      ORDER BY captured_at DESC LIMIT 1`,
    [name, hash]
  );
  if (existing.rows.length > 0) {
    return { id: existing.rows[0].id, captured_at: existing.rows[0].captured_at, isNew: false };
  }

  const inserted = await pool.query(
    `INSERT INTO doc_revisions (doc_name, content, content_hash)
     VALUES ($1, $2, $3)
     RETURNING id, captured_at`,
    [name, content, hash]
  );
  return { id: inserted.rows[0].id, captured_at: inserted.rows[0].captured_at, isNew: true };
}

async function getRevision(name, id) {
  assertKnownDoc(name);
  const { rows } = await pool.query(
    `SELECT id, doc_name, content, content_hash, captured_at
       FROM doc_revisions
      WHERE doc_name = $1 AND id = $2`,
    [name, id]
  );
  return rows[0] || null;
}

async function listHistory(name, limit = 100) {
  assertKnownDoc(name);
  const { rows } = await pool.query(
    `SELECT id, content_hash, captured_at, length(content) AS size_bytes
       FROM doc_revisions
      WHERE doc_name = $1
      ORDER BY captured_at DESC, id DESC
      LIMIT $2`,
    [name, limit]
  );
  return rows.map((r) => ({
    id: r.id,
    contentHash: r.content_hash,
    capturedAt: r.captured_at,
    sizeBytes: Number(r.size_bytes),
  }));
}

module.exports = {
  ensureSchema,
  captureIfChanged,
  getRevision,
  listHistory,
};
